name: otomasi deploy server

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      shell: bash
      env:
        GCP_CREDENTIAL: ${{ secrets.GCP_CREDENTIAL }}
      run: |
        echo "$GCP_CREDENTIAL" > ./credential.json
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/immersive-dashboard:latest
    - 
      name: multiple command
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          docker stop ${{ secrets.CNAME }}
          docker rm ${{ secrets.CNAME }}
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/immersive-dashboard:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/immersive-dashboard:latest
          docker run -d -p 80:8080 -e DBUSER=${{ secrets.DBUSER }} -e DBPASSWORD=${{ secrets.DBPASSWORD }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} -e JWT=${{ secrets.JWT }} -e ADMINPASSWORD=${{ secrets.ADMINPASSWORD }} -e GCP_PROJECTID=${{ secrets.GCP_PROJECTID }} -e GCP_BUCKETNAME=${{ secrets.GCP_BUCKETNAME }} -e GCP_PATH=${{ secrets.GCP_PATH }} --name ${{ secrets.CNAME }} ${{ secrets.DOCKERHUB_USERNAME }}/immersive-dashboard:latest
